### ISSUE TITLE
env

### ISSUE THREAD

**Issue by DollyDino99** [TongLin138/jd_cookie#1]
你这个env变量是把扫码的都上传到你的腾讯云了？？

**Comment by TongLin138** [comment]
你好，我做的就是把昨天下午三点lxk0301发的库完整拉下来，再打包放到docker hub。因为lxk0301删除了他docker hub的镜像 https://hub.docker.com/r/lxk0301/jd_cookie
 唯一一次commit也就是改个名字，我注意到了腾讯云的密钥，也是lxk0301库里的带的(https://github.com/gitupdate/test/blob/main/.env)，我没改过，如果上传，也是上传到lxk0301的手里（是如果）

**Comment by DollyDino99** [comment]
好的，明白 不过我也没搞清楚这个腾讯云的密匙是干什么的
